export const ROUTES = {
  HOME: '/',
  FLIGHT_SEARCH: '/flights/search',
  FLIGHT_DETAIL: (id) => `/flights/${id}`,
  HOTEL_SEARCH: '/hotels/search',
  HOTEL_DETAIL: (id) => `/hotels/${id}`,
  BUNDLE_SEARCH: '/bundle/search',
  CHECKOUT: '/checkout',
  BOOKING_CONFIRMATION: (id) => `/booking/confirmation/${id}`,
  MY_BOOKINGS: '/my-bookings',
  PROFILE: '/profile',
  WISHLIST: '/wishlist',
  PRICE_ALERTS: '/price-alerts',
  SAVED_SEARCHES: '/saved-searches',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  PARTNER_DEMO: '/partner-demo',
  DESTINATIONS: '/destinations',
  DEALS: '/deals',
  HELP_CENTRE: '/help',
  CONTACT_US: '/contact',
  PRIVACY_POLICY: '/privacy',
  TERMS_OF_SERVICE: '/terms',
};
